### ISSUE TITLE
Lowlight and Highlight 9.16.2 with react-syntax-highligher is broken

### ISSUE THREAD

**Issue by yyyc514** [wooorm/lowlight#19]
Not sure if this affects you individually or not. I think it would?

https://github.com/conorhastings/react-syntax-highlighter/issues/226

Your `registerLanguage` needs to support the new `rawDefinition` functionality:

https://github.com/highlightjs/highlight.js/blob/master/src/highlight.js#L904

This is required for the Arduino language (and likely others in the future).

**Comment by wooorm** [comment]
Thanks, updated!

**Comment by yyyc514** [comment]
Oh wow. That’s quite the update. Lol.

**Comment by wooorm** [comment]
It was 😉
