### ISSUE TITLE
Warning for missing `console` syntax

### ISSUE THREAD

**Issue by MoOx** [wooorm/lowlight#2]
Following this https://gitter.im/MoOx/phenomic?at=57b6202998125cfb657bc8d7

I am getting this warning.

```
Warning: %s Module build failed: Error: Expected `console` to be registered
    at coreHighlight (/Users/moox/Sync/Development/phenomic/node_modules/lowlight/lib/core.js:354:15)
    at Object.highlight (/Users/moox/Sync/Development/phenomic/node_modules/lowlight/lib/core.js:898:22)
    at visitor (/Users/moox/Sync/Development/phenomic/node_modules/remark-highlight.js/dist/index.js:36:45)
    at one (/Users/moox/Sync/Development/phenomic/node_modules/unist-util-visit/index.js:72:22)
    at all (/Users/moox/Sync/Development/phenomic/node_modules/unist-util-visit/index.js:48:26)
    at one (/Users/moox/Sync/Development/phenomic/node_modules/unist-util-visit/index.js:76:20)
    at visit (/Users/moox/Sync/Development/phenomic/node_modules/unist-util-visit/index.js:82:5)
    at /Users/moox/Sync/Development/phenomic/node_modules/remark-highlight.js/dist/index.js:42:45
    at wrapped (/Users/moox/Sync/Development/phenomic/node_modules/trough/index.js:128:19)
    at next (/Users/moox/Sync/Development/phenomic/node_modules/trough/index.js:81:24)
```

As you mentionned on the chat, this is likely due to "console" not being recognized.
Ref https://github.com/isagalaev/highlight.js/issues/1126 (as it's not in highlight.js as well for now).

I think one improvement is to make the warning message more clear. Something like

```
Lowlight expects "console" syntax language to be registered. Code can be highlighted with the appropriate syntax.
```

**Comment by MoOx** [comment]
The weird part is: webpack emit a warning, which actually is an error (modules are skipped...). Maybe you should emit a warning and not fail, as highlight.js does? (Highlight.js silently fail and does not even emit a warning actually)...
I have a website (putaindecode.io) which use a lot `console` syntax and I am afraid to update now :D

**Comment by wooorm** [comment]
Thanks for raising this here @MoOx!

Here’s the code in Highlight.js: [L495-L498](https://github.com/isagalaev/highlight.js/blob/cf2de1348459a1889a818c153003cd84d229145d/src/highlight.js#L495-L498), here’s the relative code in Lowlight: [L349-L355](https://github.com/wooorm/lowlight/blob/9f8589636cee3d7eb8a62c6a770cd347a251bdc1/lib/core.js#L349-L355).

By comparing those two, they both throw an error (albeit the Lowlight one is more cryptic, so that should be fixed).

> Highlight.js silently fail and does not even emit a warning actually

Could that be the difference between the setup in highlight and lowlight? As in, through Webpack, or remark-highlight.js? From what I read in the code, both should throw an error if the language isn’t available.

How did the previous set-up of remark-highlight handle `console` highlighting? Did it ignore the code-block? Maybe the solution is to ignore highlighting blocks with unknown flags, or warn instead of throwing?

**Comment by MoOx** [comment]
It using remark-highlight.js spawn by a webpack loader :D
I were just using remark-highlight.js which was using highlight.js directly, and I "just" upgraded to the new version using lowlight (btw, great name haha).

Previously this was not throwing any error or warning anywhere, and code block where just not highlighted (even if "rendered", see image below).

![screen shot 2016-08-19 at 12 01 58](https://cloud.githubusercontent.com/assets/157534/17806442/d73565ae-6604-11e6-9616-00bf91cf3a8b.png)

Do you need more info?

**Comment by wooorm** [comment]
> btw, great name haha

<3

> Previously this was not throwing any error or warning anywhere, and code block where just not highlighted (even if "rendered", see image below).

I think the difference in behaviour is [this line in `remark-highlight.js`](https://github.com/ben-eb/remark-highlight.js/commit/31a2d4c734aeda5d3bcab8a7e4874b9b33376951#diff-1fdf421c05c1140f6d71444ea2b27638L21), which switched from `highlightAuto` to `highlight`. The behaviour of `highlightAuto` is to ignore non-existing flags, and that of `highlight` is to throw. @ben-eb, any reason you opted to switch this?

**Comment by ben-eb** [comment]
Ah, so that's the culprit! Happy to release a patch changing this, no need for a major right?

**Comment by MoOx** [comment]
No need for a major indeed. Look like it's just a patch :)

**Comment by wooorm** [comment]
No major, I doubt people are relying on their highlighting to throw. Only case I can imagine for that is tests, but those tests are testing the wrong thing anyhow and should’ve reporter it here already :)

**Comment by ben-eb** [comment]
remark-highlight.js `4.0.1` is out with this fix.

**Comment by MoOx** [comment]
Thanks!
