### ISSUE TITLE
Are there any plans supporting 3rd party languages?

### ISSUE THREAD

**Issue by jaredlll08** [wooorm/lowlight#22]
So HighlightJS is no longer accepting new language support to their repo, and instead are encouraging people publishing their own 3rd party language support, I was wondering if you had any plans to support these languages?
(I am happy to PR the language support that I made if you are open to the idea)

**Comment by wooorm** [comment]
Probably depends on https://github.com/wooorm/lowlight/issues/21. So after that is done, I’m guessing that it’ll work.

**Comment by yyyc514** [comment]
>  I was wondering if you had any plans to support these languages?

I think you'd have to elaborate on what exactly you mean by "support"? I think the answer is "no" but a clearer description would help.

That said if you wanted to "bundle them all" (and then provide some level of support) nothing would be stopping you.

**Comment by jaredlll08** [comment]
What I am specifically asking is:

I have written language support for a language that is not included in HLJS. They are not accepting new languages so I am wondering if this project has any plans to support 3rd party languages like mine [and the others here](https://github.com/highlightjs).

By support I mean built in support like in this file: https://github.com/wooorm/lowlight/blob/master/index.js


As in, in that file there will be something along the lines of:
```javascript
low.registerLanguage('<name here>', require('<not highlight.js>/<lang>'))
```
So even though my language isn't included in hljs itself, people can still use it if they use this library.

I will say that I have had little issue with registering my language support like this <https://github.com/wooorm/lowlight#lowregisterlanguagename-syntax>, but I have a few projects that I would like my language support to be included in, as well as it would be nice for projects that use this library (like react-syntax-highlighter, which I am using) to have support for my language support by default. So I figured I would reach out and see if there were plans to include language support that hljs didn't include themselves.

**Comment by wooorm** [comment]
If `low.registerLanguage()` already works, it will keep on working, if that’s what you’re asking!
Am I correct in assuming that with react syntax highlighter, `SyntaxHighlighter.registerLanguage()` then also already works?

I’m not interested in including languages that are not in HLJS by default, in lowlight.

**Comment by jaredlll08** [comment]
> SyntaxHighlighter.registerLanguage()

Does work yes.

> I’m not interested in including languages that are not in HLJS by default, in lowlight.

That is what I was asking, thanks.

**Comment by jaredlll08** [comment]
Actually, 

> that are not in HLJS by default,

If there was a community repo / package that contained *all* the 3rd party languages, would you be interested in supporting that?

**Comment by yyyc514** [comment]
_I think it would help if you were clearer with the terminology you're using._ "support" is a little nebulous here IMHO - unless you truly meant it to be all encompassing.

Any numbers of terms might paint a clearer picture: maintain, handle issues, bundle, etc...

**We both (lowlight and HLJS) support 3rd party languages.**  For HLJS a big effort went into doing this well (package design, allowing easy building, easy to use CDN modules, etc.) - and a 3rd party grammar community popped up after that work was gone. Many of the PRs we did not merge evolved into 3rd party language modules and can used by anyone today.

**What we don't do is BUNDLE 3rd party languages.**  That's what makes them "3rd party" rather than 1st party.

**Comment by yyyc514** [comment]
```
low.registerLanguage('<name here>', require('<highlight.js>/<lang>'))
low.registerLanguage('<name here>', require('<highlight.js-community>/<lang>'))
```

This would already work today... we don't need to do anything special to support pulling in languages from a different NPM package...

**Comment by jaredlll08** [comment]
I am not asking about anything regarding HLJS itself, I am asking in the context of LowLight, I am well aware of HLJS' stance on 3rd party languages.

> This is already supported... we don't need to do anything special to support requiring languages from a different NPM package...

You completely missed what I am asking. I am saying if a community package popped up, that had *all* of the 3rd party languages (at-least the ones under the highlightjs org on github) *bundled* into a single package, would @wooorm be willing to add support for *that* package as well as the default highlightJS package, so instead of having to add **X** new deps, it would just be a single dep.

**Comment by yyyc514** [comment]
> I am not asking about anything regarding HLJS itself, I am asking in the context of LowLight,

Yes, but I find them closely related.  My rough understanding is that if HLJS suddenly supported the exact AST tree output that lowlight desired that there would be no more lowlight; ie, lowlight exists to solve a very specific problem.
 
> would @wooorm be willing to add support for that package as well as the default highlightJS package, so instead of having to add X new deps, it would just be a single dep.

Indeed I missed your point - thanks for clarifying, that's MUCH clearer. :-)  Good luck, that seems a bit more in the realm of possibility. :-)  Kind of half-bundling... and a way to add all the 3rd party language to a widely used upstream...  curious to see where this goes.

**Comment by wooorm** [comment]
> […] I am saying if a community package popped up, […] would @wooorm be willing to add support for that package as well as the default highlightJS package, so instead of having to add X new deps, it would just be a single dep.
> — @jaredlll08

This is something that you could build and maintain in userland. I prefer modules to be tiny lego building blocks that do a single thing. Lowlight is as such, and I think your proposal can be another.
