### ISSUE TITLE
Should recommend rehype-stringify

### ISSUE THREAD

**Issue by alixander** [wooorm/lowlight#24]
Using rehype on the browser imports their parser, which has parse5 in the dependency tree, a 186kb (as of today) dependency that'll never be used here. It was the largest portion of my node_modules bundle (I'm using this on browser)

Since rehype is a collection of plugins, I just used the stringify plugin and chucked the parser bloat from my bundle size. I believe this should be the recommendation in the doc here.

Happy to add a PR for the doc change if you'd like.

**Comment by wooorm** [comment]
The issue title is the inverse of what you propose, I believe.

I would agree that using unified with rehype-stringify, is acceptable. Or using hast-util-to-html.
