### ISSUE TITLE
lowlight will report an error when used with highlight.js 10.3.0

### ISSUE THREAD

**Issue by CodePlayer** [wooorm/lowlight#27]
highlight.js 10.3.0 committed a piece of code  which will cause lowlight to throw the following exception:
`Uncaught TypeError: Cannot read property 'useBR' of undefined`

The highlight's commit revision is : [https://github.com/highlightjs/highlight.js/commit/980832e3d38ce56ab50ec7359492952d2dde5237](https://github.com/highlightjs/highlight.js/commit/980832e3d38ce56ab50ec7359492952d2dde5237)

**Comment by wooorm** [comment]
thanks, fixed!

**Comment by joshgoebel** [comment]
@wooorm Pretty sure you don't use or really care about useBR in general right? You just got bit by wrapping us in a way that didn't consider we check that input?

**Comment by wooorm** [comment]
We don't use it. We do get the previous config and then after a call restore that to joy mutate global stage, but the previous config was undefined, and undefined fails when setting again.
