### ISSUE TITLE
Is there a way to add the line numbers?

### ISSUE THREAD

**Issue by lk8888** [wooorm/lowlight#28]
I want to add line numbers in code. but  I have no clue how to solve this

**Comment by wooorm** [comment]
That isn’t something I’m interested in maintaining here, but lowlight gives you access to a syntax tree, which you can [traverse](https://unifiedjs.com/learn/recipe/tree-traversal/) to do all kinds of things. See also [this related discussion](https://github.com/wooorm/refractor/issues/8).
