### ISSUE TITLE
Add example in the README to use in a React component

### ISSUE THREAD

**Issue by MoOx** [wooorm/lowlight#3]
That would be nice as I tried to use `{ lowlight.highlight("json", {somejson}).value }` and I am getting an error

```
Error: Objects are not valid as a React child (found: object with keys {type, value}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `QuickStart`.
```

I guess I am missing a specific initialization for React.

**Comment by MoOx** [comment]
I just found https://github.com/rexxars/react-lowlight, maybe I should just use that instead :D

**Comment by wooorm** [comment]
Yes, awesome! Or, alternatively, [react-syntax-highlighter](https://github.com/conorhastings/react-syntax-highlighter). (I have not used either, so don’t take my word for it!)

Can I close this?
