### ISSUE TITLE
is possible to release with a cjs module?

### ISSUE THREAD

**Issue by michelson** [wooorm/lowlight#38]
it seems that this awesome library is not easy to use in next js due to the ESM only new release. 
I know this is more an issue for next-js than this library, but just wondering if would you consider to release a cjs version of lowlight ?

**Comment by wooorm** [comment]
Hi there!

Nope. Moving to ESM-only is intentional. [More info here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). That link includes a workaround for Next
