### ISSUE TITLE
Use with webpack will throw Uncaught Error: Unknown language: `js` is not registered

### ISSUE THREAD

**Issue by zzuu666** [wooorm/lowlight#39]
`sideEffects` filed in `lowlight/package.json` is `false`, and webpack will tree shake `./lib/common.js`, so those register events will not execute.

IMO,   `lib/common.js` and `lib/all.js` are have side effects, so `sideEffects` should not be `false`.

this is an example, https://github.com/zzuu666/webpack-side-effects

Thanks.

**Comment by wooorm** [comment]
solved!

**Comment by zzuu666** [comment]
> solved! (most likely, can you check?)

yes, it works after I upgrade to 2.2.1.
