### ISSUE TITLE
re-export  highligh.js `getLanguage`

### ISSUE THREAD

**Issue by uinz** [wooorm/lowlight#42]
In order to display more uniformly, I hope to export the `getLanguage` API of `highlight.js`.

If the project installs `highlight.js` repeatedly, I am worried that it is not the same `highlight` instance

**Comment by uinz** [comment]
I am working on a markdown editor.

I hope the `language` extracted by the following shortcut keys is unified

` ```js(space) `

` ```javasscript(space)`

**Comment by wooorm** [comment]
- What is `(space)`?!
- How does such a function solve “extraction”
- `.listLanguages` and `.registered` can already do what you want?

**Comment by hanneskuettner** [comment]
Could we reopen this and reconsider it?

A valid use-case at least in my book is to resolve language aliases back to their full, canonical names or accessing their display names.
