### ISSUE TITLE
Tiny private API change

### ISSUE THREAD

**Issue by joshgoebel** [wooorm/lowlight#44]
Following our discussion I decided to rename the internals just a little (removing all mention of CSS from the abstract tree itself, as that is a concern of the renderer, not the tree).

https://github.com/highlightjs/highlight.js/commit/1db18921bbaa0f053b77a15cb417a479e81f003d

This should land in 10.6 but should be super easy for you to deal with.  I also now use a `language` attribute instead of overloading `kind` for sublanguage stuff.

**Comment by wooorm** [comment]
Closing as I didn’t notice it in 10.6. If it changes and I notice it, I’ll fix it!
