### ISSUE TITLE
Incorrect Solidity hightlighting with certain comments

### ISSUE THREAD

**Issue by eggplantzzz** [wooorm/lowlight#49]
When using lowlight to apply styling to Solidity, it incorrectly parses comments in certain cases. Consider the following code:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

contract MetaCoin {
  constructor() {
    balances[tx.origin/***stuff***/] = 10000;
  }
}
```

In particular, note the comment that comes after `tx.origin` (I know, a weird place for a comment). My setup is the following:

```
import { unified } from "unified";
import rehypeStringify from "rehype-stringify";
import { lowlight } from "lowlight/lib/core";
import { solidity } from "highlightjs-solidity";
lowlight.registerLanguage("solidity", solidity);
const processor = unified().use(rehypeStringify);
const highlighted = lowlight.highlight("solidity", source.contents);
const finishedText = processor.stringify(highlighted);
```

In `finishedText` you will notice that lowlight does not wrap the comment as a comment but rather skips the `/` and parses the `*`s as operator. However, if you put a space in the source code like `tx.origin /***stuff***/` it correctly parses it as a comment.

**Comment by wooorm** [comment]
Can you confirm the whether the same problem exists in highlight.js? This project just wraps that. It doesn't (shouldn't) change anything with how highlighting works.

**Comment by eggplantzzz** [comment]
Ah, originally I thought that highlightjs was working properly because I have another project that uses it for Solidity syntax highlighting and I thought it was working. On second look, it seems like it highlights the comment above differently, depending on whether there is a space between the variable and the `/` or not. I'll go report it on their repo, feel free to close this. Thanks!

**Comment by wooorm** [comment]
Makes sense, thanks!
