### ISSUE TITLE
Compatible with ES6 browsers

### ISSUE THREAD

**Issue by anyidea** [wooorm/lowlight#53]
![CleanShot 2023-12-20 at 18 18 23@2x](https://github.com/wooorm/lowlight/assets/48710760/16a09f24-a35b-4368-a0f7-5a4735edd808)

`Object.hasOwn()` was new feature introduced in`ES2022`, which is incompatible with old browsers like chrome older than v92

so, use `Object.prototype.hasOwnProperty.call()`  may be better.

**Comment by wooorm** [comment]
This is intentional, see the compatibility table.
Use tools like esbuild or whatever to compile JavaScript down to what you want to support.
