### ISSUE TITLE
What is devlop?

### ISSUE THREAD

**Issue by tes735** [wooorm/lowlight#57]
I'm getting an error after importing and running my implementation in tiptap that the module devlop is not found. https://github.com/wooorm/lowlight/blob/main/package.json#L37

I couldn't find this as a "thing" anywhere? A typo?

**Comment by wooorm** [comment]
It's a package

Please post your actual issue. This shouldn't be an issue. You are probably using old tools.

**Comment by tes735** [comment]
Sorry, that was the issue as I stated. When trying to run the implementation, it complains in the logs that it can't find the devlop module. It's a new project. I played around with it for a bit, but then moved on and rolled with something different. Thanks for the quick reply.

**Comment by wooorm** [comment]
> It's a new project

`devlop` can cause problems in very old tools. Create React App I think. It might be through webpack 4. CRA is no longer maintained. I don’t know tiptap but perhaps they are using old things too. I can only recommend using more recent tools.
