### ISSUE TITLE
feature request: language aliases in lowlight.listLanguages()

### ISSUE THREAD

**Issue by liyasthomas** [wooorm/lowlight#58]
Currently `lowlight.listLanguages()` gives a lowercase string array of names of all registered languages.

I was trying to render a list of all supported languages.

<img width="759" alt="Screenshot 2024-05-24 at 10 39 33 PM" src="https://github.com/wooorm/lowlight/assets/10395817/c024a0a5-510c-467b-87b8-80cf48a36537">

---

It would be great if `lowlight.listLanguages()` had languages along with their case-sensitive name, eg: JavaScript instead of javascript.

ref: https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

**Comment by joshgoebel** [comment]
It would only take a line or two to get this list by looping over languages with `getLanguage`, no?

**Comment by wooorm** [comment]
You already have the grammars, correct?

You can use them:

```js
import highlight from 'highlight.js'
import javascript from 'highlight.js/lib/languages/javascript'

console.log(javascript(highlight).name) // 'JavaScript'
```

Is that viable?

**Comment by liyasthomas** [comment]
I went with this implementation:

```javascript
import highlight from "highlight.js"
import { common, createLowlight } from "lowlight"

const lowlight = createLowlight(common)
const languages = lowlight.listLanguages()

for (const language of languages) {
  console.log(highlight.getLanguage(language)?.name);
}
